parameters:
    sfynx.tool.twig.extension.forward.class: Sfynx\ToolBundle\Twig\Extension\PiForwardExtension
    sfynx.tool.twig.extension.service.class: Sfynx\ToolBundle\Twig\Extension\PiServiceExtension
    sfynx.tool.twig.extension.jquery.class: Sfynx\ToolBundle\Twig\Extension\PiJqueryExtension
    sfynx.tool.twig.extension.date.class: Sfynx\ToolBundle\Twig\Extension\PiDateExtension
    sfynx.tool.twig.extension.tool.class: Sfynx\ToolBundle\Twig\Extension\PiToolExtension
    sfynx.tool.twig.extension.route.class: Sfynx\ToolBundle\Twig\Extension\PiRouteExtension
    sfynx.tool.twig.extension.form.class: Sfynx\ToolBundle\Twig\Extension\PiFormExtension
    sfynx.tool.twig.extension.layouthead.class: Sfynx\ToolBundle\Twig\Extension\PiLayoutHeadExtension

services:
    #
    # configuration of the twig extensions
    #
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       public: true
       tags:
           - { name: 'twig.extension' }

    twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       public: true
       tags:
           - { name: 'twig.extension' }

    twig.extension.loader:
        class: Twig_Extension_StringLoader
        public: true
        tags:
           - { name: 'twig.extension' }

    #
    # configuration of the sfynx extensions
    #
    sfynx.tool.twig.extension.forward:
        class: '%sfynx.tool.twig.extension.forward.class%'
        public: true
        arguments: ['@service_container']
        tags:
            - { name: 'twig.extension' }

    sfynx.tool.twig.extension.service:
        class: '%sfynx.tool.twig.extension.service.class%'
        public: true
        arguments: ['@service_container']
        tags:
            - { name: 'twig.extension' }

    sfynx.tool.twig.extension.jquery:
        class: '%sfynx.tool.twig.extension.jquery.class%'
        public: true
        arguments: ['@service_container', '@translator']
        tags:
            - { name: 'twig.extension' }

    sfynx.tool.twig.extension.date:
        class: '%sfynx.tool.twig.extension.date.class%'
        public: true
        arguments: ['@service_container']
        tags:
            - { name: 'twig.extension' }

    sfynx.tool.twig.extension.tool:
        class: '%sfynx.tool.twig.extension.tool.class%'
        public: true
        arguments: ['@service_container']
        tags:
            - { name: 'twig.extension' }

    sfynx.tool.twig.extension.route:
        class: '%sfynx.tool.twig.extension.route.class%'
        public: true
        arguments: ['@service_container']
        tags:
            - { name: 'twig.extension' }

    sfynx.tool.twig.extension.form:
        class: '%sfynx.tool.twig.extension.form.class%'
        public: true
        arguments: ['@service_container']
        tags:
            - { name: 'twig.extension' }

    sfynx.tool.twig.extension.layouthead:
        class: '%sfynx.tool.twig.extension.layouthead.class%'
        public: true
        arguments: ['@service_container']
        tags:
            - { name: 'twig.extension' }
