parameters:
    sfynx.tool.manager.mapper.class: Sfynx\ToolBundle\Util\PiMapperManager
    sfynx.tool.manager.db.class: Sfynx\ToolBundle\Util\PiDbManager
    sfynx.tool.manager.config.class: Sfynx\ToolBundle\Util\PiConfigManager
    sfynx.tool.manager.array.class: Sfynx\ToolBundle\Util\PiArrayManager
    sfynx.tool.manager.string.class: Sfynx\ToolBundle\Util\PiStringManager
    sfynx.tool.manager.stringcut.class: Sfynx\ToolBundle\Util\PiStringCutManager
    sfynx.tool.manager.date.class: Sfynx\ToolBundle\Util\PiDateManager
    sfynx.tool.manager.file.class: Sfynx\ToolBundle\Util\PiFileManager
    sfynx.tool.manager.file_spl.class: Sfynx\ToolBundle\Util\PiFileSplManager
    sfynx.tool.manager.curl.class: Sfynx\ToolBundle\Util\PiCurlManager
    sfynx.tool.manager.script.class: Sfynx\ToolBundle\Util\PiScriptManager
    sfynx.tool.manager.regex.class: Sfynx\ToolBundle\Util\PiRegexManager
    sfynx.tool.manager.mailer.class: Sfynx\ToolBundle\Util\PiMailerManager
    sfynx.tool.manager.rest.class: Sfynx\ToolBundle\Util\PiRestManager
    sfynx.tool.manager.log.class: Sfynx\ToolBundle\Util\PiLogManager
    sfynx.tool.manager.timer.class: Sfynx\ToolBundle\Util\PiTimerManager
    sfynx.tool.manager.encryption.class: Sfynx\ToolBundle\Util\PiEncryption
    sfynx.tool.manager.random.class: Sfynx\ToolBundle\Util\PiRandomManager
    
    sfynx.tool.manager.soapclient.class: Sfynx\ToolBundle\Util\Soap\PiSoapClientManager
    sfynx.tool.manager.soapclient.proxy.class: Sfynx\ToolBundle\Util\Soap\PiSoapProxy

services:
    #
    # configuration of the Util classes
    # 
    sfynx.tool.mapper_collection:
        class: '%sfynx.tool.manager.mapper.class%'
        
    sfynx.tool.manager.db:
        class: '%sfynx.tool.manager.db.class%'
        arguments: ['@service_container'] 
            
    sfynx.tool.array_manager:
        class: '%sfynx.tool.manager.array.class%'

    sfynx.tool.string_manager:
        class: '%sfynx.tool.manager.string.class%'
        
    sfynx.tool.string_cut_manager:
        class: '%sfynx.tool.manager.stringcut.class%'

    sfynx.tool.date_manager:
        class: '%sfynx.tool.manager.date.class%'

    sfynx.tool.file_manager:
        class: '%sfynx.tool.manager.file.class%'
        arguments: ['@service_container']  
        
    sfynx.tool.file_sql_manager:
        class: '%sfynx.tool.manager.file_spl.class%'
        arguments: ['%kernel.cache_dir%', '@logger']
        
    sfynx.tool.curl_manager:
        class: '%sfynx.tool.manager.curl.class%'
        arguments: ['@service_container']         
        
    sfynx.tool.script_manager:
        class: '%sfynx.tool.manager.script.class%'
        arguments: ['@service_container']         
        
    sfynx.tool.regex_manager:
        class: '%sfynx.tool.manager.regex.class%'
        arguments: ['@service_container']  
        
    sfynx.tool.mailer_manager:
        class: '%sfynx.tool.manager.mailer.class%'
        arguments: ['@service_container']
        
    sfynx.tool.rest_manager:
        class: '%sfynx.tool.manager.rest.class%'
        
    sfynx.tool.log_manager:
        class: '%sfynx.tool.manager.log.class%'
        arguments: ['%kernel.logs_dir%', '@logger']
        
    sfynx.tool.timer_manager:
        class: '%sfynx.tool.manager.timer.class%'
        arguments: ['@service_container']         
        
    sfynx.tool.string_manager:
        class: '%sfynx.tool.manager.string.class%'
        
    sfynx.tool.encryption_manager:
        class: '%sfynx.tool.manager.encryption.class%'
        
    sfynx.tool.random_manager:
        class: '%sfynx.tool.manager.random.class%'
        
    #
    # configuration of the Util classes
    #         
    sfynx.tool.soapclient_manager:
        class: '%sfynx.tool.manager.soapclient.class%'
        arguments: ['@service_container'] 
        
    synx.tool.soapclient_proxy:
        class: '%sfynx.tool.manager.soapclient.proxy.class%'
        arguments: ['@sfynx.tool.soapclient_manager']